
name: build-monk

on:
 workflow_dispatch:
   

jobs:
  build:
    runs-on: monkci-ubuntu-24.04-32
    strategy:
      fail-fast: false

    steps:
      - name: Free up disk space at start
        run: |
          sudo apt clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - uses: actions/checkout@v4

      - name: Setup Docker Builder
        uses: MonkCi-Inc/setup-docker-builder@v1

      - name: Verify builder
        run: |
          echo "Builder: $MONKCI_BUILDER"
          docker buildx ls
          mount | grep monkci || echo "No monkci mount found"
          
      - name: Build image
        uses: MonkCi-Inc/build-push-action@v1
        with:
          context: .
          tags: test:latest
